spring:
  profiles:
    active: dev
  application:
    name: hello-spring
  # 데이터 연결을 위한 설정
  datasource:
    url: jdbc:oracle:thin:@데이터베이스 주소 입력
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: 사용자명 입력
    password: 비밀번호 입력
  servlet:
    multipart:
      # 애플리케이션이 받을 수 있는 최대 업로드 용량(100MB)
      max-file-size: 100000000 
      # 한 유저가 업로드 할 수 있는 최대 업로드 용량(10MB)
      max-request-size: 10000000
      # JSP를 사용하기 위해 JSP 파일들의 경로를 설정. -> WebConfig.java로 설정을 이동함.
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
# mybatis 설정 파일의 경로 지정.
mybatis:
  # mybatis-config.xml 파일의 위치를 지정.
  config-location: classpath:mybatis/mybatisconfig.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/bizmatch/**/dao/mapper/*.xml

# Application 전용 설정. (Spring과 관계 없음.)
app:
  jwt:
    issuer: hello-spring-security
    secret-key: 
  iamport:
    apiKey: 
    apiSecret: 
  multipart:
    base-dir: /usr/local/src/tomcat/apache-tomcat-10.1.33/uploadfiles
    obfuscation:
      enable: true
      hide-ext:
        enable: true
  security:
    permit-all-urls:
      /api/member/signup/email/available/,
      /api/member/signin,
      /ws/**,
      /api/board,
      /api/board/view/**,
      /api/board/comment/view/**,
      /api/member/findpwd,
      /api/email/check/,
      /api/email/authnum/samecheck,
      /api/bizno/api/ask,
      /api/member/signup/**,
      /api/member/resetpwd,
  interceptor:
    accesslog:
      addpathpatterns: /**
      excludepath: /js/**,
        /css/**,
        /img/**,
        /mailhtml/**
    logincheck:
      addpathpatterns: /**
      excludepath: /,
        /member/signin/**,
        /member/select/**,
        /member/signup/**,
        /js/**,
        /css/**,
        /img/**,
        /error/**,
        /mailhtml/**,
        /bizno/**,
        /email/**
  cors:
    acceptpath:
      http://3.34.180.91,
      http://localhost:3000,
# Profile 분리
---
spring:
  config:
    activate:
      on-profile: prod

# prod profile 전용 설정
app:
  multipart:
    base-dir: /usr/local/src/tomcat/apache-tomcat-10.1.33/uploadfiles
  cors:
    acceptpath:
      http://3.34.180.91
